### PR TITLE
Logging tutorial

### PR DESCRIPTION
**Pull request by TheEpicBlock**
This pr includes a tutorial on how to upload log files. It includes a tutorial for the Vanilla and MultiMc. For Vanilla it makes use of a button to open the .minecraft folder making it os independent, this also works for custom .minecraft folders.
The tutorial has been put inside the `using` category, as it is meant for non-technical users of Fabric. The navigation.yml has also been updated to include the tutorial.

### CODE REVIEW

**Comment by gdude2002** [comment]
This looks like a good start - could you upload a screenshot of the full page? I'm not in a position to check out your fork and build the site myself at the moment.

**Comment by TheEpicBlock** [comment]
image

**Comment by gdude2002** [comment]
I think this is good overall, yup - Nice use of the horizontal rule as well. We're probably going to want to add some more info to this later and maybe formalize the structure a bit more but, until then, I'm happy to merge.

**Comment by gdude2002** [comment]
There we go. Thanks!

**Pull request merged**
